services:
  # Next.js service
  frontend:
      container_name: nextjs_app
      image: nextjs_app:1.0.0
      build:
        context: ./frontend
        dockerfile: frontend.dockerfile
      ports:
        - 3000:3000
      restart: always
      depends_on:
        - backend
  # Flask service
  backend:
    container_name: flask_app
    image: flask_app:1.0.0
    build:
      context: ./backend
      dockerfile: flask.dockerfile
    ports:
      - 3500:3500
    environment:
      - DATABASE_URI=postgresql://${POSTGRES_USER_CUSTOM}:${POSTGRES_PASSWORD_CUSTOM}@db:5433/${POSTGRES_DB_CUSTOM}
      - FLASK_DEBUG=1
      - FLASK_APP=app
      - FLASK_ENV=development
      - SECRET_KEY=${FLASK_SECRET_KEY}
    depends_on:
      - db
  # DB service
  db:
    container_name: postgres_db
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER_CUSTOM}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_CUSTOM}
      POSTGRES_DB: ${POSTGRES_DB_CUSTOM}
      PGPORT: 5433
    ports:
      - 5433:5433
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}
